export interface EasyTierConfigOptions {
  instanceName: string;
  networkName: string;
  networkSecret: string;
  hostname?: string;
  dhcp: boolean;
  noListener: boolean;
  flags: Partial<Record<EasyTierFlag, boolean>>;
  edgePeerUri?: string;
  includePublicUdpPeer: boolean;
  includePublicTcpPeer: boolean;
}

export type EasyTierFlag =
  | 'latency_first'
  | 'private_mode'
  | 'enable_exit_node'
  | 'no_tun'
  | 'use_smoltcp'
  | 'disable_ipv6'
  | 'enable_kcp_proxy'
  | 'enable_quic_proxy'
  | 'disable_p2p'
  | 'p2p_only'
  | 'multi_thread'
  | 'accept_dns';

export const EASYTIER_FLAG_ORDER: EasyTierFlag[] = [
  'latency_first',
  'private_mode',
  'enable_exit_node',
  'no_tun',
  'use_smoltcp',
  'disable_ipv6',
  'enable_kcp_proxy',
  'enable_quic_proxy',
  'disable_p2p',
  'p2p_only',
  'multi_thread',
  'accept_dns',
];

export const EASYTIER_FLAG_LABELS: Record<EasyTierFlag, string> = {
  latency_first: 'latency_first — prefer low-latency paths',
  private_mode: 'private_mode — only same network can relay through this node',
  enable_exit_node: 'enable_exit_node — act as an internet exit node',
  no_tun: 'no_tun — do not create a TUN device (relay/observe only)',
  use_smoltcp: 'use_smoltcp — userspace TCP stack',
  disable_ipv6: 'disable_ipv6',
  enable_kcp_proxy: 'enable_kcp_proxy',
  enable_quic_proxy: 'enable_quic_proxy',
  disable_p2p: 'disable_p2p — always relay, never punch',
  p2p_only: 'p2p_only — never relay',
  multi_thread: 'multi_thread',
  accept_dns: 'accept_dns',
};

export const PUBLIC_UDP_PEER = 'udp://ip.ziyourufeng.eu.org:11010';
export const PUBLIC_TCP_PEER = 'tcp://ip.ziyourufeng.eu.org:11010';

const TOML_STRING_RE = /^[^"\\\n\r]*$/;

function tomlString(value: string): string {
  if (!TOML_STRING_RE.test(value)) {
    throw new Error('value contains characters that are unsafe for a TOML string');
  }
  return `"${value}"`;
}

/**
 * Build an EasyTier client `.toml` for joining a mesh through EdgeTier as an
 * extra peer. Pure and deterministic so it can be unit-tested; the result is
 * shown/downloaded client-side only and may contain a network_secret, so it is
 * never sent to the server.
 */
export function buildEasyTierConfig(options: EasyTierConfigOptions): string {
  const lines: string[] = [];
  lines.push('# EasyTier client config generated by EdgeTier');
  lines.push('# Contains your network_secret and a tokenized WSS URI. Treat as a secret.');
  lines.push('');
  lines.push(`instance_name = ${tomlString(options.instanceName || 'home-mesh-client')}`);
  lines.push(`dhcp = ${options.dhcp ? 'true' : 'false'}`);
  lines.push(`hostname = ${tomlString(options.hostname ?? '')}`);
  if (options.noListener) lines.push('no_listener = true');
  lines.push('');
  lines.push('[network_identity]');
  lines.push(`network_name = ${tomlString(options.networkName)}`);
  lines.push(`network_secret = ${tomlString(options.networkSecret)}`);
  lines.push('');

  const peers: string[] = [];
  if (options.edgePeerUri) peers.push(options.edgePeerUri);
  if (options.includePublicUdpPeer) peers.push(PUBLIC_UDP_PEER);
  if (options.includePublicTcpPeer) peers.push(PUBLIC_TCP_PEER);
  for (const uri of peers) {
    lines.push('[[peer]]');
    lines.push(`uri = ${tomlString(uri)}`);
    lines.push('');
  }

  lines.push('[flags]');
  for (const flag of EASYTIER_FLAG_ORDER) {
    if (options.flags[flag] !== undefined) {
      lines.push(`${flag} = ${options.flags[flag] ? 'true' : 'false'}`);
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

export function defaultConfigOptions(networkName = 'home-mesh'): EasyTierConfigOptions {
  return {
    instanceName: 'home-mesh-client',
    networkName,
    networkSecret: '',
    hostname: '',
    dhcp: true,
    noListener: true,
    flags: {
      latency_first: true,
      private_mode: true,
      multi_thread: true,
      enable_exit_node: false,
      no_tun: false,
      disable_p2p: false,
    },
    edgePeerUri: undefined,
    includePublicUdpPeer: true,
    includePublicTcpPeer: true,
  };
}
